# Generated by Django 4.2.5 on 2023-09-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description_short', models.TextField(verbose_name='description_short')),
                ('description_long', models.TextField(verbose_name='description_long')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Place')),
            ],
        ),
    ]
