# Generated by Django 4.2.5 on 2023-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='position',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
