# Generated by Django 4.0 on 2023-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_images_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='places.Images'),
        ),
    ]
